lsi: false
safe: true
source: /docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: snooops.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://snooops.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /REPOSITORY-NAME/  
